name: Deploy Node.js App to Naver Cloud

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client and sshpass
      run: sudo apt-get install -y openssh-client sshpass

    - name: Access Naver Cloud Server and Deploy
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p $SSH_PASSWORD ssh -p 2222 -o StrictHostKeyChecking=no root@223.130.157.233 << EOF
          sudo yum update -y --exclude=kernel*  # 기본 시스템 업데이트, 커널 제외
          sudo yum install -y curl gcc gcc-c++ make
          
          # Node.js 18.x 버전 설치 (LTS 버전)
          curl -sL https://rpm.nodesource.com/setup_18.x | sudo bash -
          sudo yum install -y nodejs
          
          # 기존 Node.js 프로세스 종료
          pkill -f node || true  # 기존의 모든 Node.js 프로세스 종료, 프로세스가 없을 경우 오류 무시
          
          # 프로젝트 디렉토리 생성 및 이동
          mkdir -p /root/node_project
          cd /root/node_project
          
          # Git 리포지토리 클론 또는 업데이트
          if [ ! -d ".git" ]; then
            git clone https://github.com/Tekk-97/nodejs-helloworld.git .   # 리포지토리 클론
          else
            git pull origin master  # 최신 코드 가져오기
          fi

          # Node.js 서버 실행
          nohup node ./http_server.js > server.log 2>&1 &
        EOF
