name: Deploy Node.js App to Naver Cloud

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client and sshpass
      run: sudo apt-get install -y openssh-client sshpass

    - name: Access Naver Cloud Server and Deploy
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p $SSH_PASSWORD ssh -p 2222 -o StrictHostKeyChecking=no root@223.130.157.233 << EOF
          sudo yum update -y
          sudo yum install -y curl gcc gcc-c++ make
          curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
          sudo yum install -y nodejs
          
          # 프로젝트 디렉토리 생성 및 이동
          mkdir -p /root/node_project
          cd /root/node_project
          
          # Git 리포지토리 클론 또는 업데이트
          if [ ! -d ".git" ]; then
            git clone https://github.com/Tekk-97/nodejs-helloworld.git .   # 리포지토리 클론
          else
            git pull origin master  # 최신 코드 가져오기
          fi

          # Node.js 서버 실행
          node ./http_server.js  
        EOF
