name: Deploy Node.js App to Naver Cloud

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client and sshpass
      run: sudo apt-get install -y openssh-client sshpass

    - name: Access Naver Cloud Server and Deploy
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p $SSH_PASSWORD ssh -p 2222 -o StrictHostKeyChecking=no root@223.130.157.233 << EOF
          sudo yum update -y
          sudo yum install -y curl gcc gcc-c++ make
          curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
          sudo yum install -y nodejs
          cd /root/node_project   # 실제 프로젝트 디렉토리로 변경
          git pull origin main
          node ./http_server.js   # nodejs 대신 node 사용
        EOF
